# Generated by Django 2.2.2 on 2021-03-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20210311_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genter',
            new_name='Gender',
        ),
    ]
