# Generated by Django 2.2.2 on 2021-03-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20210311_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='genter',
            new_name='gender',
        ),
    ]
