# Generated by Django 2.2.2 on 2021-03-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_auto_20210313_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=1),
        ),
    ]
