# Generated by Django 2.2.2 on 2021-03-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_auto_20210313_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], max_length=1),
        ),
    ]
