# Generated by Django 2.2.2 on 2021-03-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_auto_20210313_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
