# Generated by Django 2.2.2 on 2021-03-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0005_remove_products_gender'),
        ('owner', '0009_auto_20210313_0912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
