# Generated by Django 2.2.2 on 2021-04-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_delete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
