# Generated by Django 2.2.2 on 2021-03-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_count',
            field=models.IntegerField(default=1),
        ),
    ]
