# Generated by Django 2.2.2 on 2021-03-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_shipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipaddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
