# Generated by Django 2.2.2 on 2021-03-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_shipaddress_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipaddress',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
