# Generated by Django 2.2.2 on 2021-03-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210320_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ship_id',
        ),
    ]
