# Generated by Django 2.2.2 on 2021-03-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_order_ordered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
