# Generated by Django 2.2.2 on 2021-03-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='payment_status',
        ),
    ]
