# Generated by Django 2.2.2 on 2021-03-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_cart_checkedout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkedout',
            field=models.BooleanField(default=False),
        ),
    ]
