# Generated by Django 2.2.2 on 2021-03-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image1',
        ),
    ]
