# Generated by Django 2.2.2 on 2021-03-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_profile_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
