# Generated by Django 2.2.2 on 2021-04-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_profile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipaddress',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
